export enum EventTypeEnum {
    SHIPMENT_CREATED = 'SHIPMENT_CREATED',
    SHIPMENT_UPDATED = 'SHIPMENT_UPDATED',
    SHIPMENT_CANCELLED = 'SHIPMENT_CANCELLED',
    SHIPMENT_DELIVERED = 'SHIPMENT_DELIVERED',
}